---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : movingworlds
production_url : http://www.movingworlds.com

posts:
  permalink: /:categories/:title/
  summary_lines: 20
  latest: 1

pages:
  permalink: 'pretty'