title : Moving Worlds
tagline: A Journal of Transcultural Writings
author :
  name : Moving Worlds
navigation :
  - index.html
  - scope.md
  - archive.html
  - submissions.md
  - purchase-online.md
  - editorial-team.md
  - credits.md
  - links.md
  - conferences.md
  - contact.md
  - categories.html
